title: Let it slide
description: Discover the future of technology!
theme: just-the-docs

url: https://bigballon.github.io/let-it-slide/
logo: "/assets/images/logo.png"
favicon_ico: "/assets/images/favicon.ico"

math: mathjax


aux_links:
  Github: https://github.com/BIGBALLON
  Template: https://github.com/just-the-docs/just-the-docs-template

heading_anchors: true
